const oauth = (scopes) => ({ type: "oauth2", flows: { authorizationCode: { authorizationUrl: "/oauth/authorize", tokenUrl: "/oauth/token", scopes: Object.fromEntries(scopes.map(s => [s, s])) } } });
const common = (scopes, readOnly, destructive = false) => ({
  securitySchemes: [oauth(scopes)],
  _meta: { securitySchemes: [oauth(scopes)] },
  annotations: { readOnlyHint: readOnly, openWorldHint: false, destructiveHint: destructive },
});
export const TOOL_MANIFEST = [
  { name: "list_devices", title: "List devices", description: "List GodControl devices owned by the signed-in user.", scopes: ["godcontrol.devices.read"], readOnly: true, input: {}, ...common(["godcontrol.devices.read"], true) },
  { name: "status", title: "Get device status", description: "Read heartbeat and capability status for an owned device.", scopes: ["godcontrol.devices.read"], readOnly: true, input: { device_id: { type: "string" } }, ...common(["godcontrol.devices.read"], true) },
  { name: "system_info", title: "System information", description: "Read bounded system information from an owned device.", scopes: ["godcontrol.devices.read"], readOnly: true, local: "system_info", input: {}, ...common(["godcontrol.devices.read"], true) },
  { name: "list_directory", title: "List directory", description: "List an allowed directory on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "fs_list", input: { device_id: { type: "string" }, path: { type: "string" }, depth: { type: "integer" } }, ...common(["godcontrol.fs.read"], true) },
  { name: "get_file_info", title: "Get file information", description: "Read metadata for an allowed path on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "fs_info", input: { device_id: { type: "string" }, path: { type: "string" } }, ...common(["godcontrol.fs.read"], true) },
  { name: "fs_read", title: "Read text file", description: "Read bounded UTF-8 text from an allowed file on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "fs_read", input: { device_id: { type: "string" }, path: { type: "string" }, maxBytes: { type: "integer" } }, ...common(["godcontrol.fs.read"], true) },
  { name: "search", title: "Search files", description: "Search file names below an allowed root on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "search_files", input: { device_id: { type: "string" }, root: { type: "string" }, pattern: { type: "string" }, maxResults: { type: "integer" } }, ...common(["godcontrol.fs.read"], true) },
  { name: "git_status", title: "Git status", description: "Read status for an allowed repository on an owned device.", scopes: ["godcontrol.git.read"], readOnly: true, local: "git_status", input: { device_id: { type: "string" }, repoPath: { type: "string" } }, ...common(["godcontrol.git.read"], true) },
  { name: "git_diff", title: "Git diff", description: "Read a bounded diff for an allowed repository on an owned device.", scopes: ["godcontrol.git.read"], readOnly: true, local: "git_diff", input: { device_id: { type: "string" }, repoPath: { type: "string" }, staged: { type: "boolean" } }, ...common(["godcontrol.git.read"], true) },
  { name: "start_process", title: "Start policy-controlled process", description: "Start a PTY-backed process through the local GodControl policy.", scopes: ["godcontrol.process"], readOnly: false, local: "start_process", input: { device_id: { type: "string" }, command: { type: "string" }, cwd: { type: "string" }, idempotency_key: { type: "string" } }, ...common(["godcontrol.process"], false, true) },
  { name: "read_process_output", title: "Read process output", description: "Read bounded output from a managed process.", scopes: ["godcontrol.process"], readOnly: true, local: "read_process_output", input: { device_id: { type: "string" }, session_id: { type: "string" }, idempotency_key: { type: "string" } }, ...common(["godcontrol.process"], true) },
  { name: "write_file", title: "Write text file", description: "Write an allowed UTF-8 file through the local policy.", scopes: ["godcontrol.fs.write"], readOnly: false, local: "fs_write", input: { device_id: { type: "string" }, path: { type: "string" }, content: { type: "string" }, mode: { type: "string" }, idempotency_key: { type: "string" } }, ...common(["godcontrol.fs.write"], false, true) },
  { name: "edit_block", title: "Edit exact block", description: "Replace exactly one text block through the local policy.", scopes: ["godcontrol.fs.write"], readOnly: false, local: "edit_block", input: { device_id: { type: "string" }, path: { type: "string" }, old_text: { type: "string" }, new_text: { type: "string" }, idempotency_key: { type: "string" } }, ...common(["godcontrol.fs.write"], false, true) },
  { name: "create_enrollment_code", title: "Create device enrollment code", description: "Create a short-lived one-time code for a local GodControl agent.", scopes: ["godcontrol.devices.read"], readOnly: false, input: {}, ...common(["godcontrol.devices.read"], false) },
];
export const toolByName = (name) => TOOL_MANIFEST.find(t => t.name === name);
