import { z } from "zod";

const oauth = (scopes) => ({ type: "oauth2", scopes: [...scopes] });
const common = (scopes, readOnly, destructive = false, meta = {}) => {
  const securitySchemes = [oauth(scopes)];
  return { securitySchemes, _meta: { securitySchemes, ...meta }, annotations: { readOnlyHint: readOnly, openWorldHint: false, destructiveHint: destructive } };
};
const required = (type) => ({ type, required: true });
const optional = (type) => ({ type, required: false });
const envelope = z.object({ value: z.unknown().optional(), truncated: z.boolean().optional() }).passthrough();

export const TOOL_MANIFEST = [
  { name: "list_devices", title: "List devices", description: "List GodControl devices owned by the signed-in user.", scopes: ["godcontrol.devices.read"], readOnly: true, input: {}, outputSchema: z.object({ devices: z.array(z.object({ id: z.string(), name: z.string(), status: z.record(z.string(), z.unknown()).optional() })) }), ...common(["godcontrol.devices.read"], true) },
  { name: "status", title: "Get device status", description: "Read heartbeat and capability status for an owned device.", scopes: ["godcontrol.devices.read"], readOnly: true, input: { device_id: required("string") }, outputSchema: z.object({ id: z.string(), name: z.string() }).passthrough(), ...common(["godcontrol.devices.read"], true) },
  { name: "system_info", title: "System information", description: "Read bounded system information from an owned device.", scopes: ["godcontrol.devices.read"], readOnly: true, local: "system_info", input: { device_id: required("string") }, outputSchema: envelope, ...common(["godcontrol.devices.read"], true) },
  { name: "list_directory", title: "List directory", description: "List an allowed directory on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "fs_list", input: { device_id: required("string"), path: required("string"), depth: optional("integer") }, ...common(["godcontrol.fs.read"], true) },
  { name: "get_file_info", title: "Get file information", description: "Read metadata for an allowed path on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "fs_info", input: { device_id: required("string"), path: required("string") }, ...common(["godcontrol.fs.read"], true) },
  { name: "fs_read", title: "Read text file", description: "Read bounded UTF-8 text from an allowed file on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "fs_read", input: { device_id: required("string"), path: required("string"), maxBytes: optional("integer") }, ...common(["godcontrol.fs.read"], true) },
  { name: "search", title: "Search files", description: "Search file names below an allowed root on an owned device.", scopes: ["godcontrol.fs.read"], readOnly: true, local: "search_files", input: { device_id: required("string"), root: required("string"), pattern: required("string"), maxResults: optional("integer") }, ...common(["godcontrol.fs.read"], true) },
  { name: "git_status", title: "Git status", description: "Read status for an allowed repository on an owned device.", scopes: ["godcontrol.git.read"], readOnly: true, local: "git_status", input: { device_id: required("string"), repoPath: required("string") }, ...common(["godcontrol.git.read"], true) },
  { name: "git_diff", title: "Git diff", description: "Read a bounded diff for an allowed repository on an owned device.", scopes: ["godcontrol.git.read"], readOnly: true, local: "git_diff", input: { device_id: required("string"), repoPath: required("string"), staged: optional("boolean") }, ...common(["godcontrol.git.read"], true) },
  { name: "start_process", title: "Start policy-controlled process", description: "Start a confirmation-required, allowlisted process through local GodControl policy.", scopes: ["godcontrol.process"], readOnly: false, local: "start_process", input: { device_id: required("string"), command: required("string"), cwd: optional("string"), idempotency_key: required("string") }, ...common(["godcontrol.process"], false, true) },
  { name: "read_process_output", title: "Read process output", description: "Read bounded output from a managed process.", scopes: ["godcontrol.process"], readOnly: true, local: "read_process_output", input: { device_id: required("string"), session_id: required("string"), idempotency_key: required("string") }, ...common(["godcontrol.process"], true) },
  { name: "write_file", title: "Write text file", description: "Write an allowed UTF-8 file through local policy; confirmation is required.", scopes: ["godcontrol.fs.write"], readOnly: false, local: "fs_write", input: { device_id: required("string"), path: required("string"), content: required("string"), mode: optional("string"), idempotency_key: required("string") }, ...common(["godcontrol.fs.write"], false, true) },
  { name: "edit_block", title: "Edit exact block", description: "Replace exactly one text block through local policy; confirmation is required.", scopes: ["godcontrol.fs.write"], readOnly: false, local: "edit_block", input: { device_id: required("string"), path: required("string"), old_text: required("string"), new_text: required("string"), idempotency_key: required("string") }, ...common(["godcontrol.fs.write"], false, true) },
  { name: "create_enrollment_code", title: "Create device enrollment code", description: "Create a short-lived one-time code for a local GodControl agent.", scopes: ["godcontrol.devices.read"], readOnly: false, input: {}, outputSchema: z.object({ code: z.string(), expires_in: z.number(), instructions: z.string() }), ...common(["godcontrol.devices.read"], false) },
  { name: "get_profile", title: "Get profile", description: "Read the signed-in user profile.", scopes: ["openid", "email"], readOnly: true, input: {}, outputSchema: z.object({ id: z.string(), name: z.string(), email: z.string(), nickname: z.string() }), ...common(["openid", "email"], true, false, { "openai/profile": true }) },
];
export const PUBLIC_TOOL_NAMES = new Set(TOOL_MANIFEST.map((tool) => tool.name));
export const toolByName = (name) => TOOL_MANIFEST.find((t) => t.name === name);
