import http from "node:http";
import express from "express";
import cookieParser from "cookie-parser";
import { WebSocketServer } from "ws";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";
import { loadConfig, challengeToken } from "../shared/config.js";
import { bounded, hashToken, randomToken, passwordHash } from "../shared/crypto.js";
import { MemoryStore } from "../shared/store.js";
import { PostgresStore } from "../shared/postgres.js";
import { CallQueue } from "../shared/queue.js";
import { requireScopes } from "../shared/scopes.js";
import { TOOL_MANIFEST, toolByName } from "../shared/tools.js";
import { OAuthService } from "./oauth.js";

export function createHub({ config = loadConfig(), store = config.databaseUrl ? new PostgresStore(config.databaseUrl) : new MemoryStore() } = {}) {
  const app = express(); const queue = new CallQueue(store); const oauth = new OAuthService(store, config); const online = new Map();
  app.disable("x-powered-by"); app.use(express.urlencoded({ extended: false, limit: "32kb" })); app.use(express.json({ limit: "128kb" })); app.use(cookieParser());
  const rate = new Map(); app.use((req, res, next) => { const key = `${req.ip}:${req.path}`; const now = Date.now(); const hits = (rate.get(key) ?? []).filter(t => t > now - 60_000); if (hits.length >= 120) return res.status(429).set("Retry-After", "60").json({ error: "rate_limited" }); hits.push(now); rate.set(key, hits); next(); });
  app.use((_req, res, next) => { res.set({ "Content-Security-Policy": "default-src 'none'; form-action 'self'; style-src 'unsafe-inline'", "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY", "Referrer-Policy": "no-referrer", "Permissions-Policy": "camera=(), microphone=(), geolocation=()", "Cache-Control": "no-store" }); next(); });
  const sendError = (res, code, message) => res.status(code).json({ error: "invalid_request", error_description: message });
  const auth = async (req, res, scopes = []) => { const token = await oauth.authenticate(req.get("authorization"), config.resource); if (!token) { res.set("WWW-Authenticate", `Bearer resource_metadata="${config.publicBaseUrl}/.well-known/oauth-protected-resource", error="invalid_token"`); sendError(res, 401, "authentication required"); return null; } if (!requireScopes(token.scope.split(" "), scopes)) { res.set("WWW-Authenticate", `Bearer error="insufficient_scope", scope="${scopes.join(" ")}"`); sendError(res, 403, "insufficient_scope"); return null; } return token; };
  const publicPage = (title, body) => `<!doctype html><meta charset="utf-8"><title>${title}</title><main style="font:16px system-ui;max-width:760px;margin:3rem auto">${body}</main>`;
  app.get("/", (_req, res) => res.type("html").send(publicPage("GodControl", "<h1>GodControl public MCP</h1><p>Secure remote access to an operator-owned GodControl device.</p><p><a href='/support'>Support</a> · <a href='/privacy'>Privacy</a> · <a href='/terms'>Terms</a></p>")));
  for (const [path, title, text] of [["/support", "Support", "Contact the deployment operator using the support address published with this installation."], ["/privacy", "Privacy", "GodControl processes account, device, OAuth, and audit data only to provide the requested private-device service. File contents are not retained in audit records by default."], ["/terms", "Terms", "Use GodControl only on devices and paths you own or are authorized to administer. The operator may disable access and retain security records." ]]) app.get(path, (_req, res) => res.type("html").send(publicPage(title, `<h1>${title}</h1><p>${text}</p>`)));
  app.get("/healthz", (_req, res) => res.json({ ok: true })); app.get("/readyz", (_req, res) => res.status(config.nodeEnv === "production" && !config.databaseUrl ? 503 : 200).json({ ready: config.nodeEnv !== "production" || Boolean(config.databaseUrl) }));
  app.get("/.well-known/oauth-protected-resource", (_req, res) => res.json(oauth.protectedResource())); app.get("/.well-known/oauth-authorization-server", (_req, res) => res.json(oauth.metadata()));
  app.get("/.well-known/openai-apps-challenge", (_req, res) => { const token = challengeToken(config); if (!token) return res.sendStatus(404); res.type("text/plain").send(token); });
  app.post("/oauth/register", async (req, res) => { try { res.status(201).json(await oauth.register(req.body)); } catch (e) { sendError(res, 400, e.message); } });
  app.get("/oauth/authorize", async (req, res) => { try { await oauth.authorizeForm(req.query, req, res); } catch (e) { res.status(400).type("html").send(publicPage("Authorization error", `<h1>Authorization error</h1><p>${e.message}</p>`)); } });
  app.post("/oauth/authorize", async (req, res) => { try { res.redirect(303, await oauth.authorizePost(req.body, req.cookies)); } catch (e) { res.status(400).type("html").send(publicPage("Authorization error", `<h1>Authorization error</h1><p>${e.message}</p>`)); } });
  app.post("/oauth/token", async (req, res) => { try { res.json(await oauth.token(req.body)); } catch (e) { sendError(res, 400, e.message); } });
  app.get("/oauth/userinfo", async (req, res) => { const token = await auth(req, res, ["openid", "email"]); if (token) res.json(await oauth.userinfo(token)); });
  app.post("/agent/enroll", async (req, res) => { try { const record = await store.consumeEnrollment(req.body.code ?? ""); if (!record) return sendError(res, 400, "invalid or expired enrollment code"); const deviceToken = randomToken(48); const device = await store.saveDevice({ id: `dev_${randomToken(12)}`, userId: record.userId, name: String(req.body.name ?? "GodControl device").slice(0, 100), tokenHash: hashToken(deviceToken), status: { online: false }, createdAt: Date.now() }); res.json({ device_id: device.id, device_token: deviceToken, hub_url: config.publicBaseUrl }); } catch { sendError(res, 500, "enrollment unavailable"); } });
  app.get("/agent/connect", (req, res) => { if (req.headers.upgrade?.toLowerCase() !== "websocket") return res.sendStatus(426); });

  async function handleTool(token, name, args) {
    const tool = toolByName(name); if (!tool || !requireScopes(token.scope.split(" "), tool.scopes)) throw new Error("insufficient_scope");
    if (name === "list_devices") return store.listDevices(token.userId);
    if (name === "status") { const d = await store.getDevice(token.userId, args.device_id); if (!d) throw new Error("device not found"); return { id: d.id, name: d.name, ...d.status }; }
    if (name === "create_enrollment_code") { const raw = randomToken(18); await store.createEnrollment({ codeHash: hashToken(raw), userId: token.userId, expiresAt: Date.now() + config.enrollmentTtlMs }); return { code: raw, expires_in: Math.floor(config.enrollmentTtlMs / 1000), instructions: "Run the agent with this one-time code; do not share it." }; }
    const device = await store.getDevice(token.userId, args.device_id); if (!device) throw new Error("device not found");
    const localArgs = { ...args }; delete localArgs.device_id; delete localArgs.idempotency_key;
    const call = await queue.dispatch({ userId: token.userId, deviceId: device.id, tool: tool.local, args: localArgs, idempotencyKey: args.idempotency_key, write: !tool.readOnly });
    if (call.status === "completed") return call.result; if (call.status === "failed" || call.status === "expired") throw new Error(call.error ?? "remote call failed");
    const socket = online.get(device.id); if (socket?.readyState === 1) { socket.send(JSON.stringify({ type: "wake", call_id: call.id })); for (const pending of await queue.recover(device.id)) socket.send(JSON.stringify({ type: "call", call_id: pending.id, tool: pending.tool, args: pending.args })); }
    const deadline = Date.now() + 10_000; while (Date.now() < deadline) { const current = await store.getCall(call.id); if (current.status === "completed") return current.result; if (current.status === "failed") throw new Error(current.error ?? "remote call failed"); await new Promise(r => setTimeout(r, 25)); }
    return { call_id: call.id, status: "pending", message: "Call queued; retry with the same idempotency_key for writes." };
  }
  function mcpServer(token) { const server = new McpServer({ name: "GodControl Public Hub", version: "0.1.0" }); for (const tool of TOOL_MANIFEST) { const shape = Object.fromEntries(Object.entries(tool.input).map(([key, spec]) => [key, spec.type === "integer" ? z.number().int().optional() : spec.type === "boolean" ? z.boolean().optional() : z.string().optional()])); server.registerTool(tool.name, { title: tool.title, description: tool.description, inputSchema: shape, annotations: tool.annotations, _meta: tool._meta }, async args => { try { const result = await handleTool(token, tool.name, args); return { content: [{ type: "text", text: bounded(result, config.maxResultBytes) }] }; } catch (e) { return { isError: true, content: [{ type: "text", text: String(e.message) }] }; } }); } return server; }
  app.all("/mcp", async (req, res) => { const token = await auth(req, res, []); if (!token) return; if (req.method !== "POST") return res.status(405).set("Allow", "POST").end(); const server = mcpServer(token); const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined }); await server.connect(transport); await transport.handleRequest(req, res, req.body); });
  const httpServer = http.createServer(app); const wss = new WebSocketServer({ noServer: true });
  httpServer.on("upgrade", async (req, socket, head) => { const url = new URL(req.url, config.publicBaseUrl); if (url.pathname !== "/agent/connect") return socket.destroy(); const raw = url.searchParams.get("device_token"); const device = raw && store.getDeviceByToken ? await store.getDeviceByToken(raw) : raw ? [...(store.devices?.values() ?? [])].find(d => d.tokenHash === hashToken(raw)) : null; if (!device) return socket.destroy(); wss.handleUpgrade(req, socket, head, async ws => { online.set(device.id, ws); device.status = { ...device.status, online: true, lastSeen: new Date().toISOString() }; await store.saveDevice?.(device); const sendPending = async () => { for (const call of await queue.recover(device.id)) ws.send(JSON.stringify({ type: "call", call_id: call.id, tool: call.tool, args: call.args })); }; ws.on("message", async data => { try { const msg = JSON.parse(data); if (msg.type === "status") { device.status = { ...device.status, ...msg.status, online: true, lastSeen: new Date().toISOString() }; await store.saveDevice?.(device); } if (msg.type === "wake") await sendPending(); if (msg.type === "result") { const call = await store.getCall(msg.call_id); if (call?.deviceId === device.id) await store.completeCall(msg.call_id, msg.error ? "failed" : "completed", bounded(msg.result, config.maxResultBytes), msg.error ? bounded(msg.error, 2000) : undefined); } } catch {} }); ws.on("close", async () => { online.delete(device.id); device.status = { ...device.status, online: false }; await store.saveDevice?.(device); }); await sendPending(); }); });
  return { app, httpServer, store, config, oauth, listen: (port = config.port) => new Promise(resolve => httpServer.listen(port, "127.0.0.1", () => resolve(httpServer.address().port))), close: async () => { await new Promise(resolve => httpServer.close(resolve)); await store.close?.(); } };
}
if (import.meta.url === `file://${process.argv[1]}`) createHub().listen().then(port => console.log(`GodControl hub listening on 127.0.0.1:${port}`));
